use_frameworks!

platform :ios, '9.0'

target 'UBDCollection_Example' do
  pod 'UBDCollection', :path => '../'

  target 'UBDCollection_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
